name: Static Analysis

on:
  push:
  pull_request:

jobs:
  static_analysis:
    name: Static Analysis

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP, Tools and Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-static-analysis-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Check runtime dependencies
        run: composer check-platform-reqs

      - name: Run Composer Validate
        run: composer validate

      - name: Run Composer Normalize
        run: composer-normalize --dry-run

      - name: Run PHPStan
        run: vendor/bin/phpstan --memory-limit=-1 -vvv

      - name: Run PHP-CS-Fixer
        run: vendor/bin/pint -v --test
